site_name: Massimo Costa's Personal Page
site_author: Massimo Costa

copyright: Copyright &copy; 2022, Massimo Costa

theme:
  name: 'material'

nav:
  - About Me: about.md
  - My Projects: projects.md
